#:schema https://rlbot.org/schemas/agent.json
[settings]
name = "Goddard"
loadout_file = "loadout.toml"
root_dir = ""
run_command = ".venv\\Scripts\\python.exe bot.py"
agent_id = "jwmccarthy/goddard"
logo_file = ""

[details]
description = "Recurrent Goddard policy trained in CARL"
fun_fact = "Runs a deterministic 15 Hz GRU policy"
source_link = "https://github.com/jwmccarthy/Goddard"
developer = "Jack"
language = "Python"
tags = ["1v1"]
